apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-repo-resource
  labels:
    demo: pipeline
spec:
  type: git
  params:
    - name: url
      value: https://github.com/mchmarny/tekton-labs
    - name: revision
      value: main